### ISSUE TITLE
Combine search and dropdown on the 360 page

### ISSUE THREAD

**Issue by andrew-bishop** [CodeForPhilly/paws-data-pipeline#118]
The search form on the 360 page has too many unnecessary moves for users. For better user experience we have to combine search field and dropdown menu into one field. I'm not sure if it's possible, but here is link for [example](https://react.semantic-ui.com/modules/dropdown/#types-search-selection).

**Comment by urirot** [comment]
@andrew-bishop this would be possible if we had all values in advance. in the above example you have a fixed number of items in the dropdown. 

that won't be possible in our solution since we have more than 60,000 entries and the dropdown will not handle that load. 
The search is a step to get a list of data asynchronously from the server based on a substring of the name.

closing for now
