### ISSUE TITLE
UI needs to check /api/execute response for status

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#229]
We shouldn't get timeouts on nginx if we crank the timeout high enough (ugh)  but  we should catch that or other errors.  In `handleExecute()`, before parsing the return from /api/execute we should check `response.ok`. If False, we need to display to user that an error (of type `response.status`) has occurred.

**Comment by urirot** [comment]
instead of checking the response, it is checking the content of the output file. added the error to that output file for cases that it errors. 
So now the UI will check the content of the file and there are 3 cases: 
1. running (UI will show an alert and no statistics. buttons will be disabled)
2. finished with statistics (normal view with statistics table)
3. finished with error message (alert with last error on pipeline)

**Comment by c-simpson** [comment]
@urirot   I realize I didn't fully comprehend your comment. Will you catch the case of an error (e.g., 5xx) that doesn't return any data?

**Comment by kfettich** [comment]
Stale issue
