### ISSUE TITLE
"Volunteer" Archived Records Issue: 

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#255]
From Lauren:
Segment: "Volunteer" Archived Records Issue: What is challenging here is that by looking at the info provided there is no way to actually know whether someone is an active volunteer or if they no longer volunteer. We can discuss this in more detail as it is an issue created by volgistics by not allowing us to maintain former volunteer records. They are "achieved" and no longer accessible at that point. Karla to look into if it just disappears.

**Comment by kfettich** [comment]
Spoke with Lauren and Allison at PAWS: the volgistics export only includes currently active volunteers; volunteers are regularly archived if they are on an extended hiatus, if they are an annual volunteer for Mutt Strut, or if they are banned from volunteering. If someone is removed from Volgistics it is because they no longer want to volunteer and their info isn't needed for volunteer coordination any longer. We need to consider:

1) accommodating an "archived volunteers" data upload, and 
2) consider storing volunteering data even after it's deleted from volgistics
