### ISSUE TITLE
Generate data step 1: create load_standardized_tables.py script

### ISSUE THREAD

**Issue by dsalorio** [CodeForPhilly/paws-data-pipeline#30]
This script will clean and standardize CSVs that we get from Paws, and then add them to or update them in a sqlite database.

The cleaning and standardization will create standardized columns for full name (ie last name, first name), phone, mobile, email, and a list of possible addresses. These columns will have a standard name across the tables to make matching easier and to be explicit that they don't contain raw data, eg 'matching_email', 'matching_name', 'matching_address_list', etc.

The steps are:

- [ ] 1 Change 'None' or 'NaN' value to an empty string
- [ ] 2 Cast value as string
- [ ] 3 Lowercase value
- [ ] 4 Strip leading and trailing white space
- [ ] 5 Remove punctuation by only keeping letters, numbers, dashes and white space, except for email addresses, which it will leave untouched
- [ ] 6 Replace internal multiple consecutive white spaces with a single white space
- [ ] 7 Create a name column with format "first name, last name"
- [ ] 8 Create a column of lists containing all possible address formats

Finally it will add all CSVs to a SQLite database.

**Comment by mike-bailey** [comment]
I've been taking initial cracks at this in lieu of having something non-assigned to do and because @urirot indicated at the meeting we may want each table to proactively be cleaned at the value level (whereas now in the code we clean on entry to master table) and [here was some scratch stuff I got done](https://github.com/CodeForPhilly/paws-data-pipeline/files/4189991/init.txt). Note the main differences being:
- Separation of header clean logic from cell clean logic
- keep_default_na set to False
- Check cells for 'NA' but with commented out code to handle a float - I can't tell what's worse, searching for a NA and setting it as "" or searching for NaN proper and setting it to -1 (or leaving it for that matter). Or if I'm overthinking value cleaning.

Since a lot of this is between the header work and the final SQLite load, I felt it was worth addressing here. Open to any insight.
