### ISSUE TITLE
Inconsistent date formatting from salseforcedonations exports

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#361]
This probably explains, at least in part, issue #353

![image](https://user-images.githubusercontent.com/11001850/121283631-769d9880-c8a9-11eb-87cb-31ac853447b2.png)

We could probably swizzle fields on import but it would be far preferable to get them all in ISO 8601 format.

Also, as this person seems to be a recurring donor, I wonder if we're missing Dec '20 ,  Jan '21, Feb '21 ?

**Comment by c-simpson** [comment]
It appears that we **have** been doing _some_ swizzling - the `Salesforce_PAWS Donation (all time)` file has Close and Created dates formatted as MM/DD/YYYY.  However, the `9_1_2020_TO_3_30_2021`  and `3_29_2021_6_1_2021` files have dates formatted the same way, but as TEXT, i.e., prefixed with a ' . So we may not be swizzling those. I'll dig into the code.

**Comment by kfettich** [comment]
keep in mind that for some of the recent salesforce files, we had to
manually change the column names because they don't match the code, which
means they were processed through local excel; the original files were
uploaded as-is; so maybe all we need to do is set up our code to read the
new format of the salesforce exports, so we don't have to process them
through excel?

**Comment by c-simpson** [comment]
That makes sense if they'll run that same report each time.  Can we get a pristine download, untouched by Excel to verify?  We can mark it R/O and take a hash so we know it hasn't been 'improved'.

**Comment by c-simpson** [comment]
The new file has M/D/YYYY dates. 

It looks like @dcstlouis has already solved this for volgisticsshifts (when reading from DB) using the magic `dateutil .parser.parse` : 
https://github.com/CodeForPhilly/paws-data-pipeline/blob/6427a812041f606495e1d34120bc3d1db5015b01/src/server/api/common_api.py#L96

Let's move this to the import process for all sources(so we don't have to care about formats), put dates into the DB as YYYY-MM-DD, and set the db column types to 'date' consistently.  (We might want to add the kw `dayfirst=False` on the parse call.)

**Comment by c-simpson** [comment]
@sposerina   Would it make the most sense to do this as a source normalization in `datasource_manager.py`?

**Comment by c-simpson** [comment]
It looks like pandas wants a datetime (else it will store dates as objects).  How do we force that?

**Comment by sposerina** [comment]
It probably makes the most sense to do it `clean_and_load_data.py`. IMO we should probably move away from using data science tools for doing application development things. Since we have concrete uses for this data we should define concrete tables and avoid using Pandas API calls that dynamically change the underlying structure of the table. But in the short term I'll look into doing date normalization as part of the load data flow.

**Comment by kfettich** [comment]
That's a sound suggestion, @sposerina

**Comment by jwtruver** [comment]
@sposerina  to double check this is complete and will close once confirmed.

**Comment by dkelley** [comment]
Where would someone check the "log" (grep) if a date can't be parsed? That would help if issues are still occurring?

**Comment by jwtruver** [comment]
@c-simpson  and @sposerina  to investgate 210706; one verified they will close.
