### ISSUE TITLE
RFM - Bin Definitions / Commercial Accounts

### ISSUE THREAD

**Issue by jwtruver** [CodeForPhilly/paws-data-pipeline#387]
@kfettich and Ben
Finalize the bin definitions.
Research into the "outliers" in donations and see if there is a need to split the data between individuals and commercial entities

**Comment by jwtruver** [comment]
Goal is to complete by EOW and share results with the rest of the team over slack, by Friday, 210716

**Comment by bdeck8317** [comment]
Recency: time since last donation will be compared to predefined ranges, and will get a score of 1-5; predefined ranges will be based on the full data available

Frequency: number of donations over the last 90 days will be compared to predefined ranges, and will get a score of 1-5; predefined ranges will be calculated by evaluating each member's highest donation count for any given fiscal period (quarter), and then breaking up the distribution into ranges, to create a score of 1-5

Monetary Value: a member's max donation over the last 5 years will be compared to predefined ranges and will get a score of 1-5; predefined ranges will be calculated based on the max donation for each member, segmented into ranges

**Comment by jwtruver** [comment]
Defined the logic for creating the bin definitions and updating them at regular intervals. How will Ben pull the data down?

**Comment by jwtruver** [comment]
bins were defined and commercial accounts have been excluded

**Comment by jwtruver** [comment]
removal of commercial will be done offline,
