### ISSUE TITLE
360 View: Show address info associated with latest donation

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#394]
`View360.js` appears to display the first address returned by  `/api/360/<matching_id>`. 
It's possible that in `pdp_contacts` a single **matching_id** is associated with multiple **salesforcecontacts IDs** (either the same or distinct).  We need to make sure we display the freshest address data.
As per KF on 7/19, we should take the address _from the contact_id that has the most recent donation_.

It appears this is best done on the server side: `get_360()` should return first(?), only(?) the address data from the latest donation.

**Comment by urirot** [comment]
I looked in to this.
The way it works today: 
- The API will returns all records to the UI. example: 2 records from salesforcecontacts and 1 from volgistics.
- The UI fills out the contact information by the order "salesforcecontacts" then "volgistics", and finally "shelterluvpeople". it will use data from the next source only if not found previously. so salesforce gets priority, then volgistics and then shelterluv.

Some thoughts before
- We probably still want to keep the source order so salesforce goes first etc, that was something already previously discussed. 
- For each source, we can sort multiple results in the UI by date, and begin with most recent. The only date we have is our `created_at`. So it's not when the record was inserted into the source but to our pdp_contacts. It might be more relevant moving forward as we add new records.
- Cris to address the idea about using the dontation data, that could work, but only for people who have donated. Also, maybe they changed address and didn't donate again, but fostered. in that case shelterluv would be the most up to date, and the sort by created_at column should solve it.
- Last point here - even with that, there will still be many wrong addresses, mostly for historical data. I was thinking we can show a list of "more address options" for now

@c-simpson, @kfettich any thoughts?

**Comment by c-simpson** [comment]
I'll let @kfettich   opine on priorities and showing multiple addresses.
 
Is there any reason not to include a field in pdp_contacts (source_date?) that we could use for this? This would reflect the latest date we can get from the imported data.   As usual this is more complicated the more you think about it:

- For SL, last foster/adopt event is probably a good reflection of address at that time
- For Volgistics, who knows? I assume scheduling is done via email, so address is probably not critical
-  For donations, a one-off donation is probably a good indicator of address, but a recurring donation probably isn't, as the CC is not re-validated on each charge.

**Comment by kfettich** [comment]
**Prioritizing address sources**: I know we had discussed extensively: "salesforcecontacts" then "volgistics", and finally "shelterluvpeople"; let's stick with this, but we should bring this up with Lauren (@jwtruver if you can help us remember this, I'd be eternally grateful!) 

**Prioritizing within a source**: 

- salesforce: prioritize the contact with the date of most recent donation; Lauren keeps salesforce updated and is actively managing the relationship with donors, so unless we learn otherwise, it is safe to assume the addresses are going to be up to date (for the most part)
- volgistics: quite frankly there is no reason for volunteers to update this information in the system; prioritize the address from the contact with most recent volunteer date; it can happen that someone was a volunteer a while back, then was absent for a long time, then signed up to volunteer again and somehow got assigned a new ID; 
- Shelterluv: choose the contact with date of most recent adoption/foster 

There is definitely an argument to be made about picking the contact with the most recent activity out of all the data sources, but it needs a bit more thinking about.

**showing a list of more address options**: I see no harm in doing this, but we may want to make sure we de-duplicate the addresses; I'd probably go with a dropdown of some sort, so as to not clutter the screen

**Comment by c-simpson** [comment]
@sposerina    Could we do a little address normalization (strip leading and trailing spaces, reduce multiple spaces to one) on import  to eliminate some of the sloppy typing dupes?
