### ISSUE TITLE
(Matching) New match group created unnecessarily

### ISSUE THREAD

**Issue by c-simpson** [CodeForPhilly/paws-data-pipeline#466]
Karla spotted a case where we already had a contact as (e.g.) 'Steph', but got a new donation where the name came in as 'Stephanie'. This created a new match group, even though SF **contact_id**,  last name, email were the same. 

Maybe we need to keep all the names we've ever seen associated with a contact_id?

**Comment by sposerina** [comment]
@c-simpson Is this still an issue or was it resolved in the mentioned issue?

**Comment by kfettich** [comment]
@Diegod96 - can you check this when running RFM: 
- A user with the name e.g. Jennifer Doe with the email jendoe@example.com makes a donation
- A user with the name e.g. Jen Doe with the email jendoe@example.com makes a donation
Does the RFM logic recognize that this is the same person, and pulls the donation from across both entries, or does it only run it for each separately?

**Comment by Diegod96** [comment]
@kfettich yep I can take a look at the logic.

**Comment by kfettich** [comment]
Thanks Diego! so then the expected behavior is that if there are 2 contact IDs in Salesforce associated with different versions of the same individual (e.g. Jennifer Doe and Jen Doe), if there's an additional piece of info (e.g. email or phone number) that matches both these records to the same record in Volgistics (e.g. Jen Doe) and ShelterLuv (e.g. Jen Doe), it will do so, and the values for volunteering and adoption/foster will be the same for the 2 Salesforce records, the only difference in RFM coming from the different donation histories from Salesforce
