### ISSUE TITLE
Add server logging

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#52]
add python logs in addition to the current prints of everything to a file in the /static/app/logs in the docker

**Comment by sposerina** [comment]
Flask has logging built in https://flask.palletsprojects.com/en/1.1.x/logging/. We were not seeing the logging in the console because the code was catching the exception and trying to use the print function to log the error. If we don't catch exceptions we will see error pages in the page which will help with debugging. When moving to production we can think about handling exceptions in code
